on:
  push:
    branches:
      - main

name: Build Bulldog

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          # Version or version range of Go to use
          go-version: "1.26"

      - name: go build
        id: go-build
        working-directory: app/
        run: |
          go build .
