on:
  push:
    tags:
      - v*

name: Release Bulldog Artifact

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}

      - name: go build
        id: go-build
        working-directory: app/
        run: |
          go build .
